version: '3'

volumes:
  unity_cache_data: {}

services:
  cache_server:
    image: windyakin/docker-unity-cache-server:latest
    ports:
      - 8126:8126
    volumes:
      - unity_cache_data:/srv/unity/cache
