name: Publish to Docker Hub

on:
  push:
   branches:
     - master
  schedule:
    # NOTE: Every 18:00 JST
    - cron: '0 9 * * *'

jobs:
  publish:
    matrix:
      max-parallel: 1
      versions:
        - '6.0.0'
        - '6.0.1'
        - '6.0.2'
        - '6.1.0'
        - '6.1.1'
        - '6.1.2'
        - '6.2.1'
        - '6.2.3'
        - '6.2.4'
        - '6.2.5'
        - '6.3.0'
        - '6.4.0-beta0'
        - '6.4.0-beta1'
        - '6.4.0-beta2'
        - '6.4.0-beta2'
        - '6.4.0-beta4'
        - '6.4.0'
        - 'latest'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.versions }}
          file: ./${{ matrix.versions }}/Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/windyakin/docker-unity-cache-server:${{ matrix.versions }}
            windyakin/docker-unity-cache-server:${{ matrix.versions }}
          push: true
        if: ${{ matrix.versions != 'latest' }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/windyakin/docker-unity-cache-server:latest
            windyakin/docker-unity-cache-server:latest
          push: true
        if: ${{ matrix.versions == 'latest' }}
